### ISSUE TITLE
Expandable region

### ISSUE THREAD

**Issue by Trentox** [Abwasserrohr/SKYBLOCK.SK#12]
Each player has an area in the beginning which has x blocks in each direction. But he can not use this whole area in the beginning. At the beginning, he can only use 1 / 5x blocks of the area. But he can then gradually increase his territory with talers. So whole area: x blocks; Area that you have at the very beginning: 1 / 5x; with each upgrade you get 1 / 5x ...

Example: 

Whole area of one player is 1000 blocks;
At the beginning the player has only 200 blocks. Because 1/5 of 1000 is 200.
With each upgrade he gets 200 blocks.

**Comment by Abwasserrohr** [comment]
Idea how to make this possible:

- We know border1 and border2, we could set a default size in the config. The protection could check, if the player has permissions to build, also check if he has bought the upgrades to his island to build at the location.

- This could be done by taking the bedrock and then make a new border1 and border2 for this player by calculating how much he should get, by default + bought bonus. limit this to the island radius.
