### ISSUE TITLE
 Duplicate Earth

### ISSUE THREAD

**Issue by Altonos** [Abwasserrohr/SKYBLOCK.SK#123]
*Describe the bug:*
It is possible to duplicate trees through large spruce trees, by using gravel and earth and turning rough earth craftet and the rough earth into podsol
*Steps to reproduce the bug:*
1. craft some coarse dirt
2. place it
3. place 4 spruce saplings above
4. let it grow
5. break the generated podzol blocks and profit

*Expected behavior*
The block shouldn't be converted back to prevent dirt duplication.

*Screenshots*
http://prntscr.com/mdrn1n

Skript Version: 2.3.2
Minecraft Version: 1.13.2

**Comment by Abwasserrohr** [comment]
Hello @Altonos! Thank you for reporting this bug. I actually didn't know that this happens to dirt if a spruce tree grows like that.

I'm changing SKYBLOCK.SK that it is no longer possible to revert podzol to normal dirt.
