### ISSUE TITLE
Add a default challenge

### ISSUE THREAD

**Issue by Abwasserrohr** [Abwasserrohr/SKYBLOCK.SK#187]
de.yml: Tiefsee Abenteuer:
needed: 64 sand, 2 oak boat
get(1.): 24 prismarin shards and crystals
get: 12 prismarin shards and crystals
level 4
25 experience

**Comment by Abwasserrohr** [comment]
Another one:
de.yml: Schwammige Aussichten:
Benötigt: 1 Wassereimer, 640 Wolle
Get (1.): 2xsponge, 50 experience
Get: 1 sponge, 25 experience
level 4

**Comment by Abwasserrohr** [comment]
There is already a challenge named "Lehmige aussichten" in de.yml. Better find another name for german.

**Comment by Trentox** [comment]
![unbenannt](https://user-images.githubusercontent.com/30383605/53842830-e755fc00-3fa0-11e9-9bdf-2c827f05245f.JPG)
