### ISSUE TITLE
Allow the player to disable certain ores in the generator

### ISSUE THREAD

**Issue by Abwasserrohr** [Abwasserrohr/SKYBLOCK.SK#213]
This has to be per player and done within a maximum amount of one single variable.

Also, it should be configurable between on and off. 

It would be the best if the configuration happens within a book.

https://github.com/Abwasserrohr/SKYBLOCK.SK/blob/master/SkyBlock/addons/oregenerator.sk

**Comment by AlmightyAnubis** [comment]
Insbesondere mit dem neuen Moos wäre dieses Feature zu stark. Was aber zu überlegen wäre, ist das man Buntes Terrakotta abschalten kann und dann nur nichtfarbiges bekommt. Das Farbige Terrakotta spammt glaube ich für die meisten nur unnötig die Kisten voll
