### ISSUE TITLE
on join: player gets damage

### ISSUE THREAD

**Issue by Abwasserrohr** [Abwasserrohr/SKYBLOCK.SK#22]
some players experiencing damage while joining. Maybe because they have a home set in air or something like that. Shouldn't happen.

**Comment by Vanillezucker** [comment]
Give the player invincibility for a few seconds or don't teleport them to their island home at all.

**Comment by Abwasserrohr** [comment]
Yeah, that would be an idea. But sometimes there are things, like player logs off on a island which is deleted for some reason and then falls to death on login... =(
