### ISSUE TITLE
new flag - treegrow

### ISSUE THREAD

**Issue by Flyerchen** [Abwasserrohr/SKYBLOCK.SK#296]
Please add a new flag so user can chose if trees (mostly oak in my case) only grow as small tree or as giant tree. 
Thank you =)

**Comment by Abwasserrohr** [comment]
Hey @Flyerchen, thank you for the idea.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/world/StructureGrowEvent.html could be interesting for this kind of flag.

**Comment by Abwasserrohr** [comment]
While I like the idea of this, I would only disable giant trees and not allowing toggling off the small trees, since this would make tree farming to efficient. I also don't really know if it can be prevented.

**Comment by Abwasserrohr** [comment]
I think what would be nice is a tree branch flag, which either enables tree branches or disables them. So there wouldn't be any big trees with branches, if the flag for tree branches is disabled.

**Comment by Abwasserrohr** [comment]
```
import:
	org.bukkit.event.world.StructureGrowEvent

on StructureGrowEvent:
	if "%event.getSpecies()%" is not "TREE" OR "JUNGLE" OR "ACACIA" OR "BIRCH" OR "TALL_BIRCH" OR "COCOA_TREE" OR "REDWOOD" OR "TALL_REDWOOD" OR "SMALL_JUNGLE" OR "SWAMP" OR "MEGA_REDWOOD" OR "BROWN_MUSHROOM" OR "RED_MUSHROOM" OR "DARK_OAK":
		event.setCancelled(true)
```

This is how I would do it, loads very fast that way.
